/// Utilities for turning raw conversation metadata into user-facing titles.
///
/// Agent logs sometimes contain local command wrappers and tool-control messages
/// as ordinary user text. These helpers keep those strings out of conversation
/// lists and prefer the first real task request when a generated title is noisy.

pub fn normalize_title_text(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

pub fn truncate_title(value: &str, max_chars: usize) -> String {
    let normalized = normalize_title_text(value);
    let mut chars = normalized.chars();
    let truncated = chars.by_ref().take(max_chars).collect::<String>();
    if chars.next().is_some() {
        format!("{truncated}...")
    } else {
        truncated
    }
}

pub fn title_candidate(value: &str, max_chars: usize) -> Option<String> {
    if !is_meaningful_task_text(value) {
        return None;
    }
    let title = truncate_title(value, max_chars);
    if title.is_empty() {
        None
    } else {
        Some(title)
    }
}

pub fn choose_title(
    preferred: Option<&str>,
    fallback: Option<&str>,
    max_chars: usize,
) -> Option<String> {
    preferred
        .and_then(|value| title_candidate(value, max_chars))
        .or_else(|| fallback.and_then(|value| title_candidate(value, max_chars)))
}

pub fn is_meaningful_task_text(value: &str) -> bool {
    let trimmed = value.trim();
    !trimmed.is_empty()
        && !trimmed.eq_ignore_ascii_case("No response requested.")
        && !is_control_text(trimmed)
}

pub fn is_visible_assistant_text(value: &str) -> bool {
    let trimmed = value.trim();
    is_meaningful_task_text(trimmed)
}

pub fn is_control_text(value: &str) -> bool {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return true;
    }

    let lower = trimmed.to_ascii_lowercase();
    [
        "<local-command-caveat",
        "<local-command-stdout",
        "<local-command-stderr",
        "<local-command-error",
        "<command-name",
        "<command-message",
        "<command-args",
        "<system-reminder",
        "<permissions instructions",
        "<app-context",
        "<collaboration_mode",
        "<apps_instructions",
        "<skills_instructions",
        "<plugins_instructions",
        "<environment_context",
    ]
    .iter()
    .any(|prefix| lower.starts_with(prefix))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_candidate_rejects_local_command_wrappers() {
        assert_eq!(
            title_candidate(
                "<local-command-caveat>Caveat: generated by local command.</local-command-caveat>",
                100
            ),
            None
        );
        assert_eq!(
            title_candidate("<command-name>/model</command-name>", 100),
            None
        );
    }

    #[test]
    fn choose_title_falls_back_to_first_task_text() {
        assert_eq!(
            choose_title(
                Some("<command-name>/model</command-name>"),
                Some("Implement task-based conversation titles"),
                100
            )
            .as_deref(),
            Some("Implement task-based conversation titles")
        );
    }
}
